#!/bin/bash

echo "Does not work yet"
exit 1

touch ~/.bash_aliases
pwd=`pwd`
echo "alias get='bash $pwd/get'" > ~/.bash_aliases
echo "alias submit='bash $pwd/submit'" >> ~/.bash_aliases
echo "alias test='bash $pwd/test'" >> ~/.bash_aliases
source ~/.bash_aliases
echo "Initialized exercise commands (get, submit, test)"