#!/bin/bash
orgaUrl=https://github.com/ndhbr-classroom/

# check for parameter
if [ -z "$1" ]
then
    printf "Usage $0 EXERCISE_NAME\n"
else
    # check wether folder exists
    if [ ! -d "$1" ]; then
        printf "Exercise does not exist in your space\n"
        exit 1
    fi

    cd $1
    git add .
    git commit -m "Automated commmit"
    git push -u origin master
    cd ..
fi
